name: "Honeygain Pot"
version: "2.0.1-Modified"
description: "Honeygain Pot Add-on for Home Assistant Originally based on xterna/honeygain-pot"
slug: "honeygain_pot"
codenotary: paitoon.j@tanukilab.net
startup: application
boot: auto
init: false
arch:
  - amd64
options:
  EMAIL: ''
  PASSWORD: ''
schema:
  EMAIL: str
  PASSWORD: str