name: Honeygain Pot
version: 2.0.1
description: Honeygain Pot Add-on for Home Assistant Originally based on xterna/honeygain-pot
slug: honey-pot
codenotary: paitoon.j@tanukilab.net
startup: application
init: false
boot: auto
arch:
  - amd64
options:
  EMAIL: ''
  PASSWORD: ''
schema:
  EMAIL: str
  PASSWORD: password