name: "OctoBot"
version: "2.0.14"
slug: "octobot"
description: "OctoBot trading bot"
arch: ["aarch64", "amd64", "armv7"] 
init: false 
boot: "auto" 
map: ["config:rw"]
environment:
  OCTOBOT_WEB_INTERFACE_HOST: "0.0.0.0"
panel_icon: "mdi:robot"
ports:
  "5001/tcp": 5001
ports_description:
  "5001/tcp": "OctoBot Web UI"
