name: "Tor Snowflake Proxy"
version: "1.0.0"
slug: "tor_snowflake_proxy"
description: "Official Tor Snowflake Proxy"
codenotary: paitoon.j@tanukilab.net
arch:
  - aarch64
  - amd64
  - armv7
  - i386
startup: application
boot: auto
network_host: true
image: "containers.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake:latest"